### PR TITLE
#955 - Support for runtime resolving of dependencies using delegate factories

### PR DESCRIPTION
**Pull request by ambvdijk**
#955

### CODE REVIEW

**Comment by brockallen** [comment]
CLA signed?

**Comment by ambvdijk** [comment]
Yes!

**Comment by brockallen** [comment]
Ok, thanks for the effort on this!

**Comment by ambvdijk** [comment]
Your welcome. Small change, lots of research ;-)

**Comment by brockallen** [comment]
Also many thanks to @alexmg for adding to the conversation.

**Pull request merged**
