### PR TITLE
Remove Transitive Dependency on System.Web

### PR DESCRIPTION
**Pull request by thefringeninja**
All tests pass, but I don't think this is being tested.

`System.IdentityModel.Tokens.Jwt` has a dependency on `System.Web.Extensions` (which also has a dependency on `System.Web` so I can't get rid of that. However ilmerge is not bringing `System.Web` through so I can live with that.

### CODE REVIEW

**Comment by brockallen** [comment]
Thanks! Dom will merge it in later.

**Comment by leastprivilege** [comment]
thanks!

**Comment by leastprivilege** [comment]
oh - could you please sign the CLA?

**Comment by thefringeninja** [comment]
you mean https://cla.dotnetfoundation.org/? I already did :)

On Thu, Feb 19, 2015 at 12:24 AM, Dominick Baier <notifications@github.com>
wrote:

> oh - could you please sign the CLA?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/Thinktecture.IdentityServer3/pull/934#issuecomment-74970652>
> .
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
