### PR TITLE
Allow Client Credentials flow for any client

### PR DESCRIPTION
**Pull request by leastprivilege**

### CODE REVIEW

**Comment by leastprivilege** [comment]
@brockallen this is a 1.2 feature - need to update EF schema as well then.

**Comment by brockallen** [comment]
Looks good, thanks!

**Comment by johnkors** [comment]
Naming is hard :)

I was bit confused by the naming of this new property, ```AllowClientCredentialsOnly ```. In my ears it sounds like it's allowing only one flow - client cred flow. It's usage seems to me that it's more ```AllowClientCredentialsTrotzdemOtherFlowDefinedForClient```. 

[1.3.0 Client.cs](https://github.com/IdentityServer/IdentityServer3/blob/1.3.0/source/Core/Models/Client.cs#L79)

```
private async Task<ValidationResult> ValidateClientCredentialsRequestAsync(NameValueCollection parameters)
{
      if (_validatedRequest.Client.Flow != Flows.ClientCredentials)
            {
                if (_validatedRequest.Client.AllowClientCredentialsOnly == false)
                {
                    LogError("Client not authorized for client credentials flow");
                    return Invalid(Constants.TokenErrors.UnauthorizedClient);
                }
            }
 }
```

Or what does the ```only``` part represent here?

**Comment by leastprivilege** [comment]
well - only - without user credentials ;)

**Comment by johnkors** [comment]
Ah, only in the sense of client credentials being a lesser kind of priveledge than flows related to user credentials (which have client AND the user involved). Not only as in "just this". Gotcha.

**Pull request merged**
