### PR TITLE
Added the ability for custom code logging in to Identity Server (conceptual)

### PR DESCRIPTION
**Pull request by flytzen**
- Added a class to IdentityServer (IdentityServerLogin) that custom code running on the host can use to log in to to log in to IdentityServer and setting authentication cookies by passing in an ExternalIdentity.

#833

*Notes*
** Please feel free to reject this PR, I won't be offended, promise ;) **
I do understand that this issue has not been agreed to be implemented and I also think that my implementation here leaves a number of things to be desired, not least the naming and error handling, which I don't think is quite in keeping with the rest of the project (I wasn't quite sure about where to put this or the best way to handle the errors).
I wanted to show an example implementation and provide a boundary around what I think it needs to do - which isn't a huge amount. Of course, the awful hacks around autofac that are required may make this a bit of a maintenance headache down the road.

This commit does not have unit tests as the code works directly with autofac which makes it rather complicated.

*Usage*
This sample middleware shows how to use it. Note that if using app.Map to load IdSrv, this middleware must be loaded in the same app.Map as IdSrv to make sure the cookie path is correct and that autofac is available:

    public class DummyIdpMiddleWare
    {
        private readonly Func<IDictionary<string, object>, Task> next;

        public DummyIdpMiddleWare(Func<IDictionary<string, object>, Task> next)
        {
            this.next = next;
        }

        public async Task Invoke(IDictionary<string, object> environment)
        {
            var context = new Microsoft.Owin.OwinContext(environment);
            if (context.Request.Path.StartsWithSegments(new PathString("/secretsquirrel")))
            {
                // You should also limit to POSTs probably
                // Here you should evaluate the user input to make sure it is all correct, like checking a SAML token or whatever
                // If you felt particularly foolish you could even use Basic Auth here :) Or two-legged oAuth 1 for custom integrations etc
                
                var externalLogin = new ExternalIdentity()
                {
                    ProviderId = "secretSquirrelId",
                    Provider = "Secret Squirrel",
                    Claims = new List<Claim>
                                                         {
                                                            new Claim(Constants.ClaimTypes.Name, "Billy Bob"),
                                                            new Claim(Constants.ClaimTypes.Role, "Boss")
                                                         }
                };
                // This is the integration point to IdSrv - this will set an auth cookie
                var idSrvLogin = new IdentityServerLogin(environment);
                var result = await idSrvLogin.LogInToIdentityServer(externalLogin);

                // TODO: Check the result here

                // Redirect the user to the Relying Party, which will send the user straight back to IdSrv to get an OIDC token
                context.Response.Redirect("https://localhost:44303/Home/About");
                // TODO: Consider returning here instead of invoking the next middleware
            }
            await this.next.Invoke(environment);
        }
    }

### CODE REVIEW

**Comment by leastprivilege** [comment]
..and have you tried that already against the nuget version of idsrv?

**Comment by flytzen** [comment]
Well, no, because I need this new class inside IdSrv for it to work. But maybe I am not understanding what you are asking?

I *did* try to make an example where I just take all of this code out of IdSrv completely and I got it working fine (I just needed to copy a few more bits of code) - see here for a working example: https://github.com/flytzen/IdPInitiatedSSOWithIdentityServer 

*However* - that example only works when running against the (unchanged) source code of IdSrv. This is because the Autofac assembly is *inlined* in IdSrv. If I try to pull off this trick with the Nuget package and all the custom code in my own assembly then my code can't use the Autofac instance I pull out of the OwinContext because it was made with the inlined version of the Autofac assembly. I had some fun trying to get that to work :)

**Comment by leastprivilege** [comment]
OwinContext is internalized as well (the purpose of the unit test that you needed to change was to catch that). 

You can run the build script to create the ilmerged nuget package. That's a good test for modifications.

**Comment by flytzen** [comment]
Ah, doh! Gotcha. Will try that.

**Comment by flytzen** [comment]
@leastprivilege Thanks for the tip about using the Nuget package - I guess you had figured out that I would have a problem with IOwinContex :)
I have now changed it to use IDictionary<string, object> and that works perfectly with the Nuget packages. I have reverted the change to the unit test as I no longer need to expose an internalised interface and I have updated the usage example in my first comment.

**Comment by flytzen** [comment]
FYI, I now have an Identity Server running with this code that accepts IdP-initiated SAML in UAT, planning to put it into production soon :)

**Comment by leastprivilege** [comment]
We gonna add an API like this soon. So it is good to hear it is working for you!

**Comment by flytzen** [comment]
Cool - should we close this PR if you are adding it elsewhere?

**Comment by leastprivilege** [comment]
Leave it open for now.

**Comment by brockallen** [comment]
IssueLoginCookie API added to dev. Please try it out and let us know if it helps.

**Comment by flytzen** [comment]
Awesome, thanks! Have been away for the weekend but will get on this asap.

**Comment by edwinf** [comment]
@flytzen did you ever get a chance to port this to the IssueLoginCookie API?  If so, do you have an example of how you did it?  I'm running into the need for this as well.

**Comment by flytzen** [comment]
No I haven’t yet, sorry – it’s been uber manic. It is still on my list to do as soon as possible.

**Comment by dahlsailrunner** [comment]
I would really love to see a sample of this.  If I can get something working I can even add some documentation.  Any chance someone has done this using the IssueLoginCookie method?

**Comment by tvdburgt** [comment]
@dahlsailrunner here's a really simple snippet I added to `LocalRegistrationController` (See `CustomUserService` sample):

        [Route("core/localregistration")]
        [HttpPost]
        public ActionResult Index(string signin, LocalRegistrationModel model)
        {
            // Register user here...

            var login = new AuthenticatedLogin
            {
                IdentityProvider = Constants.BuiltInIdentityProvider,
                Subject = Guid.NewGuid().ToString(),
                Name = model.Username
            };

            var env = Request.GetOwinContext().Environment;
            env.IssueLoginCookie(login);
            var msg = env.GetSignInMessage(signin);
            return Redirect(msg.ReturnUrl);
        }

It has no error handling etc., but simulating a user login seems to work for me.

**Comment by dahlsailrunner** [comment]
I actually got something working for this, but did not end up using the IssueLoginCookie method but rather the initial approach suggested by @flytzen.
I documented what I did to get this working here on the AuthServices repo (it's Step 5):
https://github.com/KentorIT/authservices/blob/master/doc/IdentityServer3Okta.md

**Comment by jmwnoble** [comment]
@dahlsailrunner  we followed your instructions in the link above, which works but only when it triggers an SP-initiated SSO attempt after the RP redirects to connect/authorize and then login?signin=xxx.  
Is this how it is meant to work or do we have some other issue (it appears that session and idsrv cookies are not set on the first redirect to identityserver connect/authorize?

**Comment by dahlsailrunner** [comment]
I *think* it's working the way mine is -- the basic flow of what I did is:

- IdP-initiated request comes in to Id Srv from Okta
- Configuration of the IdP within IdSrv redirects to an ANONYMOUS page on your client / app website
- That anonymous page sends a formal connect/authorize request with a specified idp on the acr_values, which redirects to Okta.  Since user is already signed in there, it just comes back to id srv and hits the AuthenticateExternalAsync method of your user service, where you can add any claims you need, and finally....
- gets redirected to the standard redirect url if coming from the RP.

If that's what is working for you, then yes.  The reason I had to do it this way is because the username and an access token is not all that my application needs.  It requires a user lookup to get permissions type settings (i.e. claims) that I could not get injected on the idp-initiated request's first pass through id srv.  

Does that answer your question?

**Comment by jmwnoble** [comment]
Thanks @dahlsailrunner that explains the IDP receiving an SP-initiated request (the bit where it redirects to Okta in your third bullet point).  The thing is that we don't need any extra info (at least we don't need any additional claims for the app - not sure if the users unique identifier within the IDP counts within that), but I can't work out whether there is a way to avoid the additional round trip to the IDP and get the session setup after the redirection from our anon page in our app.  From your investigate and work are you aware if it is possible?  Thanks

**Comment by dahlsailrunner** [comment]
Sorry to say I'm not aware.  We've always needed the claims so I never really sought an answer for what was possible if they weren't needed.

**Comment by jmwnoble** [comment]
Ok.  We'll leave it like that for now then - thanks for your prior work on it.

**Pull request closed without merging**
